### ISSUE TITLE
[Bug]: Slight formatting issue on Burt

### ISSUE THREAD

**Issue by jeremy-hill** [cwjoshuak/lostarktimer.app-web#10]
**Describe the bug**
Slight formatting issue on Burt

**To Reproduce**
Burt has either just a Seria card, or Seria card + something else, and the following HTML is displayed:

`<span class="text-[#00b5ff]">Seria Card][Legendary Rapport Item</span>`
Screenshot example: https://i.imgur.com/N9q4tRm.png

**Expected behavior**
The opening [ and closing ] are missing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 100.0.4896.127 (Official Build) (64-bit)

**Comment by alairon** [comment]
I can corroborate that there is an issue when a merchant is selling multiple noteworthy items.

I investigated the network data coming in from the server and noticed that it's already presented that way. I don't think the issue comes from the site itself, but somewhere between SaintBot and the WebSocket we're pulling the data from.
![WebSocketPayload](https://user-images.githubusercontent.com/28322630/167237736-1e6d7052-202f-419c-808c-25d591b08ed6.png)

**Comment by cwjoshuak** [comment]
![image](https://user-images.githubusercontent.com/15935660/167239477-88a5ddde-187a-4e53-8763-a66b6e4c7e8e.png)

Here is an example of how SaintBot displays its data, as when the user votes for a merchant, potentially two items can be selected. The data that I get from SaintBot has the outer `[ ]` stripped, so we're left with `Madnick Card][Legendary Rapport Item`. 

Following the example above, I can probably modify this to say `Madnick Card + Legendary Rapport Item` with the correct colors.
